### ISSUE TITLE
Please add ARMv9.2, SVE2, Dot Product and Neon support

### ISSUE THREAD

**Issue by Chess321** [pkrisz99/Renegade#20]
It's sad that it's not possible to compile the newest version on Android and Linux devices.

**Comment by pkrisz99** [comment]
While I personally haven't tried it, in the case of ARM you should be able to compile the engine for your target device. It will just not use AVX2 specific instructions, and revert to using whatever optimizations your compiler can come up with.

Linux is supported, and I recall someone else doing an Android compilation as well.

Considering you opened the same issue in *seventy-three* other repositories, please provide logs proving that you actually did attempt to compile, and to help me track down the error, if there's any.
